services:
  sqlpage:
    image: lovasoa/sqlpage:v0.33.1
    ports:
      - 3000:8080
    volumes:
      - .:/var/www # Where your SQL files are stored
      #/etc/sqlpage: the directory where your sqlpage.json configuration file⁠
    environment:
      SQLPAGE_ENVIRONMENT: development
      DATABASE_URL: postgresql://$DB_USER:$DB_PASS@postgres:$DB_PORT/$DB_NAME
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_HOST:$DB_PORT:5432
